### ISSUE TITLE
Passing in InputObjectType to an arg causes Nexus Error: this should never happen

### ISSUE THREAD

**Issue by hrgui** [prisma-labs/nexus#214]
#69 is similar to this, however error message that returns if the user does the wrong path is confusing.

## Reproduction

**INCORRECT CODE**
```js

const SongInput = inputObjectType({
  name: "SongInput",
  definition(t) {
    t.string('title', {nullable: true})
    t.string('artist', {nullable: true})
  }
});

const createSong = mutationField('createSong', {
  type: Model,
  args: {
    record: SongInput
  },
  resolve:(_, {record}, {dataSources: {rtdb}}) => {
    return rtdb.firebaseCreate(`song`,record);
  }
});
```

causes error: 
```
Error: Nexus Error: This should never happen, please check your code or open a GitHub ticket if you believe this is an issue with Nexus
    at invariantGuard (/projects/graphql-nexus/firebase-example/node_modules/nexus/dist/builder.js:709:15)
    at SchemaBuilder.getOrBuildType (/projects/graphql-nexus/firebase-example/node_modules/nexus/dist/builder.js:526:9)
    at SchemaBuilder.getInputType (/projects/graphql-nexus/firebase-example/node_modules/nexus/dist/builder.js:500:25)
    at /projects/graphql-nexus/firebase-example/node_modules/nexus/dist/builder.js:417:48
    at Array.forEach (<anonymous>)
    at SchemaBuilder.buildArgs (/projects/graphql-nexus/firebase-example/node_modules/nexus/dist/builder.js:414:27)
    at SchemaBuilder.buildObjectField (/projects/graphql-nexus/firebase-example/node_modules/nexus/dist/builder.js:396:24)
    at /projects/graphql-nexus/firebase-example/node_modules/nexus/dist/builder.js:377:44
    at Array.forEach (<anonymous>)
    at SchemaBuilder.buildObjectFields (/projects/graphql-nexus/firebase-example/node_modules/nexus/dist/builder.js:376:16)
```

https://github.com/prisma/nexus/blob/develop/src/builder.ts#L1481

**CORRECT CODE**
```js

const SongInput = inputObjectType({
  name: "SongInput",
  definition(t) {
    t.string('title', {nullable: true})
    t.string('artist', {nullable: true})
  }
});

const createSong = mutationField('createSong', {
  type: Model,
  args: {
    record: arg({type: SongInput}) // the diff is here
  },
  resolve:(_, {record}, {dataSources: {rtdb}}) => {
    return rtdb.firebaseCreate(`song`,record);
  }
});
```

## Expected
Would expect an error like, `Did you forget to pass in arg(...) for an argument?`, because that was the case here.

**Comment by tgriesser** [comment]
Rather than making this a better error, I think we should also consider allowing an input object type placed here to automatically be an `arg` the `arg` wrapping is mostly for type consistency, and we actually have an `.asArg` method on input objects to do the wrapping. It'd be simple to detect valid inputs and automatically wrap.

This is also exactly why we have this catch-all guard, to find code-paths that never happen and figure out how to improve the experience, though we should probably change to:

```
Error: Nexus Error: This codepath should never happen, please open a GitHub 
issue to help us understand how you got here :)
```

**Comment by tgriesser** [comment]
This syntax should be supported in 0.12.0-rc.4. Please let me know if you're still having issues.
