### ISSUE TITLE
Runtime error: `dynamicOutputProperty` is not a function

### ISSUE THREAD

**Issue by peterp** [prisma-labs/nexus#245]
I'm following the guide for `nexus-prisma`, but I'm getting the following error during runtime:

```
packages/nexus-prisma/index.js:877
        return nexus_1.dynamicOutputProperty({
                       ^

TypeError: nexus_1.dynamicOutputProperty is not a function
    at NexusPrismaBuilder.getCRUDDynamicOutputMethod (/Users/peterp/Personal/hammer/create-hammer-app/packages/nexus-prisma/index.js:877:24)
    at NexusPrismaBuilder.getNexusPrismaMethod (/Users/peterp/Personal/hammer/create-hammer-app/packages/nexus-prisma/index.js:867:18)
    at nexusPrismaPlugin (/Users/peterp/Personal/hammer/create-hammer-app/packages/nexus-prisma/index.js:1185:20)
```

I noticed that there are a few commits related to fixing `dynamicOutputProperty`, and a bunch of commits related to new `beta` releases, but none of them seem to be released?

Does anyone know which combinations of `nexus`, `nexus-prisma` and `prisma2` work together?

**Comment by jasonkuhrt** [comment]
Hey @peterp for now please refer to the https://github.com/prisma-labs/nexus-prisma/tree/master/examples/blog.

The guides and docs will be updated soon. I've been saying that for a while but really they will. Thanks for your patience!

Related to https://github.com/prisma-labs/nexus/issues/186
