### ISSUE TITLE
Error when using interfaceType and implements()

### ISSUE THREAD

**Issue by ujwal-setlur** [prisma-labs/nexus#361]
Here is a code snippet that is causing an error:

```ts
import {
  interfaceType,
  objectType,
  queryType,
  stringArg
} from 'nexus';

const Node = interfaceType({
  name: 'Node',
  definition(t) {
    t.id('id', { description: 'Unique identifier for the resource' });
    t.resolveType(() => null);
  }
});

const User = objectType({
  name: 'User',
  definition(t) {
    t.implements(Node); // <--- this causes the error!
    t.string('username');
    t.string('email');
  }
});

const theSchema = makeSchema({ types: [User] });
```

Error is:
```bash
Unhandled rejection Error: Expected [object Object] to be an interfaceType, saw GraphQLScalarType
    at SchemaBuilder.getInterface (/home/bytedev/micro-api/node_modules/nexus/src/builder.ts:1251:13)
    at /home/bytedev/micro-api/node_modules/nexus/src/builder.ts:852:52
    at Array.map (<anonymous>)
    at interfaces (/home/bytedev/micro-api/node_modules/nexus/src/builder.ts:852:36)
    at resolveThunk (/home/bytedev/micro-api/node_modules/graphql/type/definition.js:438:40)
    at defineInterfaces (/home/bytedev/micro-api/node_modules/graphql/type/definition.js:619:20)
    at GraphQLObjectType.getInterfaces (/home/bytedev/micro-api/node_modules/graphql/type/definition.js:587:31)
    at typeMapReducer (/home/bytedev/micro-api/node_modules/graphql/type/schema.js:276:28)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/home/bytedev/micro-api/node_modules/graphql/type/schema.js:145:28)
    at makeSchemaInternal (/home/bytedev/micro-api/node_modules/nexus/src/builder.ts:1593:18)
    at makeSchema (/home/bytedev/micro-api/node_modules/nexus/src/builder.ts:1616:49)
    at Service.started (/home/bytedev/micro-api/src/api.service.ts:25:27)
```

My packages:
```js
"devDependencies": {
    "@types/bluebird": "3.5.29",
    "@types/graphql": "14.5.0",
    "@types/jest": "24.9.0",
    "@types/node": "13.1.8",
    "@types/node-fetch": "2.5.4",
    "@typescript-eslint/eslint-plugin": "2.17.0",
    "@typescript-eslint/parser": "2.17.0",
    "eslint": "6.8.0",
    "eslint-config-airbnb-base": "14.0.0",
    "eslint-config-prettier": "6.9.0",
    "eslint-plugin-import": "2.20.0",
    "eslint-plugin-prettier": "3.1.2",
    "jest": "24.9.0",
    "jest-cli": "24.9.0",
    "moleculer-repl": "0.6.2",
    "prettier": "1.19.1",
    "ts-jest": "24.3.0",
    "ts-node": "8.6.2",
    "typescript": "3.7.5"
  },
  "dependencies": {
    "amqplib": "0.5.5",
    "apollo-server": "2.9.16",
    "esm": "3.2.25",
    "graphql": "14.5.8",
    "moleculer": "0.14.0-beta7",
    "moleculer-decorators": "1.1.1",
    "moleculer-service-ts": "1.0.2",
    "nexus": "0.12.0-rc.5",
    "winston": "3.2.1",
    "winston-gelf-transporter": "1.0.1"
  }
```

**Comment by ujwal-setlur** [comment]
Thanks for the quick fix, will test tomorrow!

**Comment by tgriesser** [comment]
Great! Released in `0.12.0-rc.6`

**Comment by ujwal-setlur** [comment]
The original problem is fixed, but I do get a typescript error:

```ts
const NodeType = interfaceType({
  name: 'Node',
  description:
    'A Node is a resource with a globally unique identifier',
  definition(t) {
    t.id('id', {
      description: 'Primary key of the resource',
      resolve(root, args, ctx, info) {
        return `${info.parentType.name}:${root.id}`;
      }
    });
    t.resolveType(() => null);
  }
});

export const User = objectType({
  name: 'User',
  definition(t) {
    t.implements(NodeType);
    t.string('username');
    t.string('email');
  }
});
```

```bash
src/graphql/schema/common.ts:17:48 - error TS2339: Property 'id' does not exist on type '{ email: string; username: string; }'.

return `${info.parentType.name}:${root.id}`;
```

**Comment by ujwal-setlur** [comment]
Any update on my previous comment? Should I open a new issue? The code runs with ts-node, but does not compile with tsc.

**Comment by lukeramsden** [comment]
@ujwal-setlur I just got this issue too, and it would appear to be caused by `NexusGenRootTypes` not including the ID from the Node interface in the User type, and the type definition for the `FieldResolver` uses `NexusGenRootTypes` and not `NexusGenFieldTypes`, which _does_ have the ID field from the Node interface.

```typescript
export interface NexusGenRootTypes {
  User: { // root type
    avatar?: string | null; // String
    dateOfBirth: any; // Date!
    email: string; // String!
    //...
  }
  Node: NexusGenRootTypes['User'];
}
export interface NexusGenFieldTypes {
  User: { // field return type
    avatar: string | null; // String
    dateOfBirth: any; // Date!
    email: string; // String!
    //...
  }
  Node: { // field return type
    id: string; // ID!
  }
}
type FieldResolver= (root: RootValue<TypeName> /*...*/);
type RootValue<TypeName extends string> = GetGen2<"rootTypes", TypeName>;
```

I would assume this is a bug, although I may be wrong, I don't know. For now I am just `@ts-ignore`ing it.

**Comment by ujwal-setlur** [comment]
@lukeramsden, thanks for the info. Looks like graphql-nexus is in a bit of flux as code is moving into different packages. For now, I have gone back to TypeGraphQL and am quite happy with it.
